DjangoProject/DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Resume.urls'))
]

DjangoProject/Resume/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', resumeUpload)
]

DjangoProject/Resume/models.py
from django.db import models

STATE_CHOICE = (
    ('Andhra Pradesh', 'Andhra Pradesh'),
    ('Arunachal Pradesh', 'Arunachal Pradesh'),
    ('Assam', 'Assam'),
    ('Bihar', 'Bihar'),
    ('Chhattisgarh', 'Chhattisgarh'),
    ('Goa', 'Goa'),
    ('Gujarat', 'Gujarat'),
    ('Haryana', 'Haryana'),
    ('Himachal Pradesh', 'Himachal Pradesh')
)


class Resume(models.Model):
    name = models.CharField(max_length=50)
    dob = models.DateField(auto_now=False, auto_now_add=False)
    gender = models.CharField(max_length=100)
    locality = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    pin = models.PositiveIntegerField()
    state = models.CharField(max_length=100, choices=STATE_CHOICE)
    mobile = models.PositiveIntegerField()
    email = models.EmailField()
    job_city = models.CharField(max_length=50)
    profile_image = models.ImageField(upload_to='profileimg', blank=True)
    my_file = models.FileField(upload_to='doc', blank=True)

    def __str__(self):
        return f"{self.id}-{self.name}-{self.dob}-{self.gender}-{self.locality}-{self.city},{self.pin}-{self.state}-{self.mobile}" \
               f"{self.email}-{self.job_city}-{self.profile_image}-{self.my_file}"




# Create your models here.

DjangoProject/Resume/forms.py
from django import forms
from .models import *

GENDER = (
    ('Male', 'Male'),
    ('Female', 'Female')
)
JOB_CITY_CHOICE = (
    ('Delhi', 'Delhi'),
    ('Pune', 'Pune'),
    ('Ranchi', 'Ranchi'),
    ('Mumbai', 'Mumbai'),
    ('Dhanbad', 'Dhanbad'),
    ('Banglore', 'Banglore'),
)


class ResumeForm(forms.ModelForm):
    gender = forms.ChoiceField(choices=GENDER, widget=forms.RadioSelect)
    job_city = forms.MultipleChoiceField(label='Perferred Job Locations', choices=JOB_CITY_CHOICE, widget=forms.CheckboxSelectMultiple)
    class Meta:
        model = Resume
        fields = ['name', 'dob', 'gender', 'locality', 'city', 'pin', 'state', 'mobile', 'email', 'job_city', 'profile_image', 'my_file']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'dob': forms.TextInput(attrs={'class': 'form-control'}),
            'locality': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'pin': forms.TextInput(attrs={'class': 'form-control'}),
            'state': forms.Select(attrs={'class': 'form-control'}),
            'mobile': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
        }

DjangoProject/Resume/views.py
from django.shortcuts import render
from .forms import *
from .models import *
# Create your views here.


def resumeUpload(request):
    msg = ""
    if request.method == 'POST':
        form = ResumeForm(request.POST)
        form.save()
        msg = "Resume Submited Successfully"
    form = ResumeForm()
    return render(request, 'home.html', {'forms': form, 'msg': msg})

DjangoProject/Resume/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'Resume/css/home.css' %}">
    <style>
        #id_gender, #id_job_city{
list-style-type:none;
display:inline;
}
    </style>
</head>
<body>
<div class="container">
    <h2 class="alert alert-danger text-center">Resume Uploader</h2>
    <div class="row">
        <div class="col-sm-6">
            {% if msg %}
                <p class="alert alert-success" id="successmsg".>{{ msg }}</p>
             {% endif%}
            <form action="" method="post" enctype="multipart/form-data" class="shadow p-5">
                {% csrf_token %}
                    {{forms}}
                <input type="submit" value="submit" class="btn btn-primary">
            </form>
        </div>
        <div class="col-md-6">

        </div>
    </div>
</div>
</body>
</html>